services:
  user:
    build: .
    environment:
      - DB_NAME=${USERS_DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${USERS_DB_HOST}

      - PORT=${USER_PORT}
    restart: always
    depends_on:
      usersdb:
        condition: service_healthy
    command: ./main
  
  usersdb:
    environment:
      - POSTGRES_DB=${USERS_DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    image: postgres
    restart: always
    volumes:
      - usersdbdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  adminer:
    container_name: adminer

    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080

volumes:
  gamesdbdata: null
  usersdbdata: null
